### ISSUE TITLE
integrate issue template

### ISSUE THREAD

**Issue by gearsdigital** [gearsdigital/kirby-reporter#12]
Add a configurable issue template as outlined in [get kirby forum](https://forum.getkirby.com/t/kirby-reporter-plugin-report-issues-from-the-panel/14684/4)

```
reporter:
  fields:
    issue:
      type: text
    browser:
      type: select
      options:
        - Chrome
        - Firefox
        - Safari
```

Would result in

```
# Issue

Here is my issue description.

# Browser

Firefox
```
